{{ if or .Values.certs.apiServer.cert .Values.certs.apiServer.key }}
apiVersion: v1
kind: Secret
metadata:
  name: tigera-apiserver-certs
  namespace: {{.Release.Namespace}}
type: Opaque
data:
  apiserver.crt: {{ required "must set apiServer.cert if apiServer.key is set" .Values.certs.apiServer.cert | b64enc }}
  apiserver.key: {{ required "must set apiServer.key if apiServer.cert is set" .Values.certs.apiServer.key | b64enc }}
{{ end }}
