{{ if .Values.prometheus.enabled }}
# This section configures the Calico Enterprise Prometheus deployment.
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: calico-node-prometheus
  namespace: tigera-prometheus
spec:
  baseImage: {{ .Values.prometheus.image }}
  nodeSelector:
    kubernetes.io/os: linux
  serviceAccountName: prometheus
  serviceMonitorSelector:
    matchLabels:
      team: network-operators
  podMonitorSelector:
    matchLabels:
      team: network-operators
  version: {{ .Values.prometheus.tag }}
  retention: 24h
  resources:
    requests:
      memory: 400Mi
  ruleSelector:
    matchLabels:
      role: tigera-prometheus-rules
      prometheus: calico-node-prometheus
  alerting:
    alertmanagers:
      - namespace: tigera-prometheus
        name: calico-node-alertmanager
        port: web
        scheme: http
{{ end }}
