{{ if or .Values.certs.manager.cert .Values.certs.manager.key }}
apiVersion: v1
kind: Secret
metadata:
  name: manager-tls
  namespace: {{.Release.Namespace}}
type: Opaque
data:
  cert: {{ required "must set manager.cert if manager.key is set" .Values.certs.manager.cert | b64enc }}
  key: {{ required "must set manager.key if manager.cert is set" .Values.certs.manager.key | b64enc }}
{{ end }}
