action: init
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: egress-with-noselector
  namespace: "{{.Namespace}}"
  labels:
    churn-k8s: "one-fish"
spec:
  podSelector:
    matchLabels:
      egress-with-noselector: 'yes'
  egress:
    - {}
