action: update
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: egress-with-noselector
  namespace: "{{.Namespace}}"
spec:
  podSelector:
    matchLabels:
      egress-with-noselector: 'yes'
  egress:
    - {}
