---
layout: null
---

---
apiVersion: projectcalico.org/v3
kind: NetworkPolicy
metadata:
  name: allow-tigera.allow-performance-hotspots
  namespace: tigera-intrusion-detection
spec:
  tier: allow-tigera
  order: 1
  selector: app == 'performance-hotspots'
  types:
  - Ingress
  - Egress
  egress:
  - action: Allow
    protocol: TCP
    destination:
      namespaceSelector: projectcalico.org/name == 'tigera-guardian'
      selector: k8s-app == 'tigera-guardian'
      ports:
      - 8080
  - action: Allow
    protocol: UDP
    destination:
      namespaceSelector: projectcalico.org/name == 'kube-system'
      selector: k8s-app == 'kube-dns'
      ports:
      - 53
  - action: Allow
    protocol: UDP
    destination:
      namespaceSelector: projectcalico.org/name == "openshift-dns"
      selector: dns.operator.openshift.io/daemonset-dns == "default"
      ports: [5353]
---
apiVersion: projectcalico.org/v3
kind: NetworkPolicy
metadata:
  name: allow-tigera.elasticsearch-access-performance-hotspots
  namespace: tigera-guardian
spec:
  tier: allow-tigera
  order: 1
  selector: k8s-app == 'tigera-guardian'
  types:
  - Ingress
  ingress:
  - action: Allow
    destination:
      ports:
      - 8080
    protocol: TCP
    source:
      namespaceSelector: projectcalico.org/name == 'tigera-intrusion-detection'
      selector:  app == 'performance-hotspots'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: performance-hotspots-deployment
  namespace: tigera-intrusion-detection
  labels:
    app: performance-hotspots
spec:
  replicas: 1
  selector:
    matchLabels:
      app: performance-hotspots
  template:
    metadata:
      labels:
        app: performance-hotspots
    spec:
      imagePullSecrets:
      - name: tigera-pull-secret
      containers:
      - name: performance-hotspots
        image: {{page.registry}}{% include component_image component="performance_hotspots" %}
        resources:
          requests:
            memory: 1G
        securityContext:
          privileged: true
          allowPrivilegeEscalation: true
        startupProbe:
          httpGet:
            path: /ph/ping
            port: 8000
            scheme: HTTP
          initialDelaySeconds: 20
          periodSeconds: 20
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 15
        readinessProbe:
          httpGet:
            path: /ph/ping
            port: 8000
            scheme: HTTP
          periodSeconds: 20
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /ph/ping
            port: 8000
            scheme: HTTP
          periodSeconds: 60
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 5
        env:
          - name: ELASTIC_HOST
            value: "tigera-secure-es-gateway-http.tigera-elasticsearch.svc"
          - name: CLUSTER_NAME
            value: "cluster"
          - name: ELASTIC_PORT
            value: "9200"
          - name: ES_CA_CERT
            value: /certs/es-ca.pem
          - name: ELASTIC_USER
            valueFrom:
              secretKeyRef:
                key: username
                name: tigera-ee-performance-hotspots-elasticsearch-access
          - name: ELASTIC_PASSWORD
            valueFrom:
              secretKeyRef:
                key: password
                name: tigera-ee-performance-hotspots-elasticsearch-access
          - name: PH_NEED_API
            value: "True"
        volumeMounts:
          - name: host-volume
            mountPath: /home/idsuser/performance_hotspots/models
          - name: es-certs
            mountPath: /certs/es-ca.pem
            subPath: es-ca.pem
        command: ["python3"]
        args: ["-m", "ph"]
      volumes:
        - name: es-certs
          secret:
            defaultMode: 420
            items:
              - key: tls.crt
                path: es-ca.pem
            secretName: tigera-secure-es-gateway-http-certs-public
        - name: host-volume
          hostPath:
            path: /var/log/calico/performance_hotspots
