{{ if .Values.packetCaptureAPI }}
{{ if .Values.packetCaptureAPI.enabled }}
{{ $spec := omit .Values.packetCaptureAPI "enabled" }}

apiVersion: operator.tigera.io/v1
kind: PacketCaptureAPI
metadata:
  name: tigera-secure
spec:
{{ $spec | toYaml | indent 2 }}

{{ end }}
{{ end }}
