---

# Required RBAC:
# - watch/list nodes and pods
kind: ServiceAccount
apiVersion: v1
metadata:
  name: tigera-panorama-controller
  namespace: tigera-firewall-integration

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tigera-panorama-controller
rules:
  - apiGroups: ["projectcalico.org"]
    resources: ["globalnetworksets"]
    verbs: ["get","list","create","update","delete"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tigera-panorama-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tigera-panorama-controller
subjects:
- kind: ServiceAccount
  name: tigera-panorama-controller
  namespace: tigera-firewall-integration

---

# The actual tigera-panorama-controller deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tigera-panorama-controller
  namespace: tigera-firewall-integration
  labels:
    k8s-app: tigera-panorama
spec:
  replicas: 1
  strategy:
     type: Recreate
  selector:
    matchLabels:
      k8s-app: tigera-panorama
  template:
    metadata:
      name: tigera-panorama-controller
      namespace: tigera-firewall-integration
      labels:
        k8s-app: tigera-panorama
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      serviceAccountName: tigera-panorama-controller
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
        - key: node-role.kubernetes.io/control-plane
          effect: NoSchedule
      imagePullSecrets:
        - name: tigera-pull-secret
      containers:
        - name: tigera-panorama-controller
          image: quay.io/tigera/firewall-integration:v3.20.0-1.0
          imagePullPolicy: IfNotPresent
          env:
            - name: ENABLED_CONTROLLERS
              value: "panorama-address-groups"
            - name: LOG_LEVEL
              value: "info"
            - name: FW_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  name: tigera-panorama-controller-config
                  key: tigera.firewall.host
            - name: FW_USERNAME
              valueFrom:
                secretKeyRef:
                  name: panorama-access
                  key: panorama.username
            - name: FW_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: panorama-access
                  key: panorama.password
            - name: FW_PANORAMA_TAGS
              valueFrom:
                configMapKeyRef:
                  name: tigera-panorama-controller-config
                  key: tigera.firewall.panorama.tags
