---

# Required RBAC:
# - watch/list nodes and pods
kind: ServiceAccount
apiVersion: v1
metadata:
  name: tigera-policy-integration-controller
  namespace: tigera-firewall-integration

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tigera-policy-integration-controller
rules:
    # This allows get, create and update access to the Calico Tiers.
  - apiGroups: ["projectcalico.org"]
    resources: ["tiers"]
    verbs: ["get","create","update"]
    # This allows read access to the Calico GlobalNetworkPolicies.
  - apiGroups: ["projectcalico.org"]
    resources: ["tier.globalnetworkpolicies"]
    verbs: ["get","create","list","update","delete"]
    # This allows read access to the Calico GlobalNetworkSets.
  - apiGroups: ["projectcalico.org"]
    resources: ["globalnetworksets"]
    verbs: ["get","create","list","update","delete"]
    # Events posts require the following access.
  - apiGroups: [""] # "" indicates the core API group
    resources: ["pods"]
    verbs: ["post","get","list"]
  - apiGroups: [""] # "" indicates the core API group
    resources: ["events"]
    verbs: ["post","get"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tigera-policy-integration-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tigera-policy-integration-controller
subjects:
- kind: ServiceAccount
  name: tigera-policy-integration-controller
  namespace: tigera-firewall-integration

---

# The actual tigera-policy-integration-controller deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tigera-policy-integration-controller
  namespace: tigera-firewall-integration
  labels:
    k8s-app: tigera-panorama
spec:
  replicas: 1
  strategy:
     type: Recreate
  selector:
    matchLabels:
      k8s-app: tigera-panorama
  template:
    metadata:
      name: tigera-policy-integration-controller
      namespace: tigera-firewall-integration
      labels:
        k8s-app: tigera-panorama
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      serviceAccountName: tigera-policy-integration-controller
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
        - key: node-role.kubernetes.io/control-plane
          effect: NoSchedule
      imagePullSecrets:
        - name: tigera-pull-secret
      containers:
        - name: tigera-policy-integration-controller
          image: quay.io/tigera/firewall-integration:v3.19.1
          imagePullPolicy: IfNotPresent
          env:
            - name: ENABLED_CONTROLLERS
              value: "panorama-policy,panorama-address-groups"
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: tigera-policy-integration-controller-config
                  key: firewall.policy.integration.log-level
            - name: FW_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  name: tigera-policy-integration-controller-config
                  key: panorama.host
            - name: FW_USERNAME
              valueFrom:
                secretKeyRef:
                  name: panorama-access
                  key: panorama.username
            - name: FW_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: panorama-access
                  key: panorama.password
            - name: FW_DEVGROUP
              valueFrom:
                configMapKeyRef:
                  name: tigera-policy-integration-controller-config
                  key: panorama.device-group
            - name: FW_PANORAMA_FILTER_TAGS
              valueFrom:
                configMapKeyRef:
                  name: tigera-policy-integration-controller-config
                  key: panorama.rules.filter
            - name: FW_POLICY_TIER
              valueFrom:
                configMapKeyRef:
                  name: tigera-policy-integration-controller-config
                  key: tigera.policy.integration.tier
            - name: FW_POLICY_TIER_ORDER
              valueFrom:
                configMapKeyRef:
                  name: tigera-policy-integration-controller-config
                  key: tigera.policy.integration.tier.order
            - name: FW_PANORAMA_TAGS
              valueFrom:
                configMapKeyRef:
                  name: tigera-policy-integration-controller-config
                  key: panorama.address-groups.filter
