# Tier containing policies to allow access to Calico Enterprise.
apiVersion: projectcalico.org/v3
kind: Tier
metadata:
  name: allow-tigera
spec:
  order: 100

---

# Allow the Kubernetes API Server access to Calico Enterprise API Server.
apiVersion: projectcalico.org/v3
kind: NetworkPolicy
metadata:
  name: allow-tigera.cnx-apiserver-access
  namespace: tigera-system
spec:
  order: 1
  tier: allow-tigera
  selector: k8s-app == 'tigera-apiserver'
  types:
  - Ingress
  ingress:
  - action: Allow
    protocol: TCP
    source:
      # This policy allows Calico Enterprise API Server access from anywhere: replace it with
      # the addresses of your Kubernetes API Servers if those are static.
      nets: ["0.0.0.0/0"]
    destination:
      # The ports Calico Enterprise API Server and Calico Enterprise Query Server are configured to listen on.
      ports: [443, 5443, 8080, 10443]

---

# This manifest creates a network policy to allow traffic to Alertmanager
# (TCP port 9093).
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: calico-node-alertmanager
  namespace: tigera-prometheus
spec:
  ingress:
  - ports:
    - port: 9093
      protocol: TCP
  podSelector:
    matchLabels:
      alertmanager: calico-node-alertmanager
      app: alertmanager
---

# This manifest creates a network policy to allow traffic between
# Alertmanagers for HA configuration (TCP port 6783).
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: calico-node-alertmanager-mesh
  namespace: tigera-prometheus
spec:
  ingress:
  - from:
    - podSelector:
        matchExpressions:
        - key: app
          operator: In
          values:
          - alertmanager
        - key: alertmanager
          operator: In
          values:
          - calico-node-alertmanager
    ports:
    - port: 9094
      protocol: TCP
    - port: 9094
      protocol: UDP
  podSelector:
    matchLabels:
      alertmanager: calico-node-alertmanager
      app: alertmanager
---

# This manifest creates a network policy to allow traffic to access the
# Prometheus (TCP port 9090).
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: prometheus
  namespace: tigera-prometheus
spec:
  ingress:
  - ports:
    - port: 9090
      protocol: TCP
  podSelector:
    matchLabels:
      app: prometheus
      prometheus: calico-node-prometheus

---

# This policy ensures Fluentd POD is marked as protected by compliance (network access report).
# Deny all traffic to Guardian (which provides access to Elasticsearch in management plane)
# except for port 8080 and allow any other egress traffic (e.g. for kube-dns).
apiVersion: projectcalico.org/v3
kind: NetworkPolicy
metadata:
  name: allow-tigera.allow-fluentd-node
  namespace: tigera-fluentd
spec:
  tier: allow-tigera
  egress:
  - action: Deny
    destination:
      selector: k8s-app == "tigera-guardian"
      namespaceSelector: projectcalico.org/name == "tigera-guardian"
      notPorts:
      - 8080
    protocol: TCP
    source: {}
  - action: Allow
  order: 1
  selector: k8s-app == "fluentd-node"
  types:
  - Ingress
  - Egress

---

# Creates a network policy to allow traffic through Guardian (TCP port 8080) to the management plane.
apiVersion: projectcalico.org/v3
kind: NetworkPolicy
metadata:
  name: allow-tigera.guardian-access
  namespace: tigera-guardian
spec:
  selector: k8s-app == 'tigera-guardian'
  tier: allow-tigera
  types:
    - Ingress
  ingress:
    - action: Allow
      destination:
        ports:
          - 8080
      protocol: TCP
      source:
        namespaceSelector: projectcalico.org/name == 'tigera-fluentd'
        selector: k8s-app == 'fluentd-node'
    - action: Allow
      destination:
        ports:
          - 8080
      protocol: TCP
      source:
        namespaceSelector: projectcalico.org/name == 'tigera-compliance'
        selector: k8s-app == 'compliance-benchmarker'
    - action: Allow
      destination:
        ports:
          - 8080
      protocol: TCP
      source:
        namespaceSelector: projectcalico.org/name == 'tigera-compliance'
        selector: k8s-app == 'compliance-reporter'
    - action: Allow
      destination:
        ports:
          - 8080
      protocol: TCP
      source:
        namespaceSelector: projectcalico.org/name == 'tigera-compliance'
        selector: k8s-app == 'compliance-snapshotter'
    - action: Allow
      destination:
        ports:
          - 8080
      protocol: TCP
      source:
        namespaceSelector: projectcalico.org/name == 'tigera-compliance'
        selector: k8s-app == 'compliance-controller'
    - action: Allow
      destination:
        ports:
          - 8080
      protocol: TCP
      source:
        namespaceSelector: projectcalico.org/name == 'tigera-intrusion-detection'
        selector: k8s-app == 'intrusion-detection-controller'
    - action: Allow
      destination:
        ports:
          - 8080
      protocol: TCP
      source:
        namespaceSelector: projectcalico.org/name == 'tigera-intrusion-detection'
        selector: job-name == 'intrusion-detection-es-job-installer'

---

kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: default-deny
  namespace: tigera-compliance
spec:
  podSelector:
    matchLabels: {}

---

kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: default-deny
  namespace: tigera-prometheus
spec:
  podSelector:
    matchLabels: {}

---

kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: default-deny
  namespace: tigera-guardian
spec:
  podSelector:
    matchLabels: {}
