action: update
kind: NetworkPolicy
apiVersion: projectcalico.org/v3
metadata:
  name: ingress-with-noselector
  namespace: "{{.Namespace}}"
  labels:
    churner: "whoohooo"
spec:
  selector: ingress-with-noselector == 'yes'
  ingress:
    - action: Allow
  types:
    - Ingress
