---
# Honeypod Fake Service

# Deployment:
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tigera-internal-dashboard
  namespace: tigera-internal
spec:
  selector:
    matchLabels:
      app: tigera-internal-dashboard
  replicas: 1
  template:
    metadata:
      labels:
        app: tigera-internal-dashboard
    spec:
      hostNetwork: false
      hostIPC: false
      hostPID: false
      imagePullSecrets:
        - name: tigera-pull-secret
      containers:
        - name: tigera-internal-dashboard
          image: quay.io/tigera/honeypod-exp-service:v3.19.2
          ports:
            - containerPort: 8888
            - containerPort: 443
          resources:
            limits:
              cpu: 100m
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 200Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            runAsGroup: 10001
            runAsNonRoot: true
            runAsUser: 10001
            seccompProfile:
              type: RuntimeDefault
      serviceAccountName: tigera-honeypod
---
# Create two service, one unreachable, one debug
kind: Service
apiVersion: v1
metadata:
  name: tigera-dashboard-internal-debug
  namespace: tigera-internal
  labels:
    app: tigera-dashboard-internal-debug
spec:
  ports:
    - port: 8888
      protocol: TCP
      targetPort: 8080
  selector:
    app: tigera-internal-dashboard
---
kind: Service
apiVersion: v1
metadata:
  name: tigera-dashboard-internal-service
  namespace: tigera-internal
  labels:
    app: tigera-dashboard-internal-service
spec:
  ports:
    - port: 443
      protocol: TCP
  selector:
    app: tigera-internal-dashboard
---
# Global Alert Template and Global Alert for Fake Service access
apiVersion: projectcalico.org/v3
kind: GlobalAlertTemplate
metadata:
  name: honeypod.fake.svc
spec:
  description: "Alerts on Honeypod accessed via fake debug service"
  summary: "[Honeypod] Fake debug service accessed by ${source_namespace}/${source_name_aggr} on port 8080"
  severity: 100
  dataSet: flows
  query: 'dest_namespace="tigera-internal" AND "dest_labels.labels"="app=tigera-internal-dashboard" AND dest_port="8080" AND reporter="dst"'
  aggregateBy:
    [source_namespace, source_name_aggr, dest_namespace, dest_name_aggr, host]
---
apiVersion: projectcalico.org/v3
kind: GlobalAlert
metadata:
  name: honeypod.fake.svc
spec:
  description: "[Honeypod] Fake debug service accessed by ${source_namespace}/${source_name_aggr} on port 8080"
  severity: 100
  dataSet: flows
  query: 'dest_namespace="tigera-internal" AND "dest_labels.labels"="app=tigera-internal-dashboard" AND dest_port="8080" AND reporter="dst"'
  aggregateBy:
    [source_namespace, source_name_aggr, dest_namespace, dest_name_aggr, host]
