---
# Honeypod IP Enumeration

# Daemonset Deployment:
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: tigera-internal-app
  namespace: tigera-internal
spec:
  selector:
    matchLabels:
      app: tigera-internal-app
  template:
    metadata:
      labels:
        app: tigera-internal-app
    spec:
      hostNetwork: false
      hostIPC: false
      hostPID: false
      imagePullSecrets:
        - name: tigera-pull-secret
      containers:
        - name: tigera-internal-app
          image: quay.io/tigera/honeypod:v3.19.2
          resources:
            limits:
              cpu: 100m
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 200Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            runAsGroup: 10001
            runAsNonRoot: true
            runAsUser: 10001
            seccompProfile:
              type: RuntimeDefault
      serviceAccountName: tigera-honeypod
---
# Global Alert Template and Global Alert for IP Enumeration
apiVersion: projectcalico.org/v3
kind: GlobalAlertTemplate
metadata:
  name: honeypod.ip.enum
spec:
  description: "Alerts on Honeypod accessed via IP enumeration"
  summary: "[Honeypod] Pod subnet IP enumeration by ${source_namespace}/${source_name_aggr}"
  severity: 100
  dataSet: flows
  query: 'dest_namespace="tigera-internal" AND "dest_labels.labels"="app=tigera-internal-app" AND reporter="dst"'
  aggregateBy:
    [source_namespace, source_name_aggr, dest_namespace, dest_name_aggr, host]
---
apiVersion: projectcalico.org/v3
kind: GlobalAlert
metadata:
  name: honeypod.ip.enum
spec:
  description: "[Honeypod] Pod subnet IP enumeration by ${source_namespace}/${source_name_aggr}"
  severity: 100
  dataSet: flows
  query: 'dest_namespace="tigera-internal" AND "dest_labels.labels"="app=tigera-internal-app" AND reporter="dst"'
  aggregateBy:
    [source_namespace, source_name_aggr, dest_namespace, dest_name_aggr, host]
---
# Global Alert Template and Global Alert for IP Enumeration
apiVersion: projectcalico.org/v3
kind: GlobalAlertTemplate
metadata:
  name: honeypod.port.scan
spec:
  description: "Alerts on Honeypod accessed via port scan"
  summary: "[Honeypod] Pod subnet port scan by ${source_namespace}/${source_name_aggr}"
  severity: 100
  dataSet: flows
  query: 'dest_namespace="tigera-internal" AND "dest_labels.labels"="app=tigera-internal-app" AND reporter="dst"'
  aggregateBy:
    [source_namespace, source_name_aggr, dest_namespace, dest_name_aggr, host]
  metric: count
  condition: gte
  threshold: 4
---
apiVersion: projectcalico.org/v3
kind: GlobalAlert
metadata:
  name: honeypod.port.scan
spec:
  description: "[Honeypod] Pod subnet port scan by ${source_namespace}/${source_name_aggr}"
  severity: 100
  dataSet: flows
  query: 'dest_namespace="tigera-internal" AND "dest_labels.labels"="app=tigera-internal-app" AND reporter="dst"'
  aggregateBy:
    [source_namespace, source_name_aggr, dest_namespace, dest_name_aggr, host]
  metric: count
  condition: gte
  threshold: 4
