---
# Honeypod Vulnerable Service

# Deployment:
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tigera-internal-db
  namespace: tigera-internal
spec:
  selector:
    matchLabels:
      app: tigera-internal-db
  replicas: 1
  template:
    metadata:
      labels:
        app: tigera-internal-db
    spec:
      hostNetwork: false
      hostIPC: false
      hostPID: false
      imagePullSecrets:
      - name: tigera-pull-secret
      securityContext:
        runAsUser: 999
        runAsGroup: 999
      containers:
      - name: tigera-internal-db
        image: mysql:8.0.22
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ALLOW_EMPTY_PASSWORD 
          value: 'yes'
        resources:
          limits:
            cpu: 100m
            memory: 400Mi
          requests:
            cpu: 100m
            memory: 400Mi
        securityContext:
            privileged: false
            allowPrivilegeEscalation: false
---
# Create Mysql service
kind: Service
apiVersion: v1
metadata:
  name: tigera-internal-backend
  namespace: tigera-internal
  labels:
    app: tigera-internal-backend
spec:
  ports:
    - port: 3306
      protocol: TCP
      targetPort: 3306
  selector:
    app: tigera-internal-db
---
# Global Alert Template and Global Alert for Vulnerable Service access
apiVersion: projectcalico.org/v3
kind: GlobalAlertTemplate
metadata:
  name: honeypod.vuln.svc
spec:
  description: "Alerts on Honeypod accessed via vulnerable (MySQL) service"
  summary: "[Honeypod] Vulnerable service (MySQL) accessed by ${source_namespace}/${source_name_aggr}"
  severity: 100
  dataSet: flows
  query: 'dest_namespace="tigera-internal" AND "dest_labels.labels"="app=tigera-internal-db" AND reporter="dst"'
  aggregateBy: [source_namespace, source_name_aggr, dest_namespace, dest_name_aggr, host.keyword]
---
apiVersion: projectcalico.org/v3
kind: GlobalAlert
metadata:
  name: honeypod.vuln.svc
spec:
  description: "[Honeypod] Vulnerable service (MySQL) accessed by ${source_namespace}/${source_name_aggr}"
  severity: 100
  dataSet: flows
  query: 'dest_namespace="tigera-internal" AND "dest_labels.labels"="app=tigera-internal-db" AND reporter="dst"'
  aggregateBy: [source_namespace, source_name_aggr, dest_namespace, dest_name_aggr, host.keyword]
---