kind: ConfigMap
apiVersion: v1
metadata:
  name: calico-config
  namespace: kube-system
data:
  etcd_endpoints: "<ETCD_ENDPOINTS>"

  etcd_ca: "/calico-secrets/etcd-ca"
  etcd_cert: "/calico-secrets/etcd-cert"
  etcd_key: "/calico-secrets/etcd-key"

---

kind: OAuthClient
apiVersion: v1
metadata:
 name: cnx-manager
redirectURIs:
 - "https://<CNX_MANAGER_ADDR>/login/oauth/callback" 
grantMethod: prompt

