[template]
src = "bird.cfg.template"
dest = "/etc/calico/confd/config/bird.cfg"
prefix = "/calico/"
keys = [
    "/bgp/v1/host",
    "/bgp/v1/global",
    "/resources/v3/projectcalico.org/externalnetworks",
    "/resources/v3/projectcalico.org/bgpfilters",
    "/resources/v3/projectcalico.org/bfdconfigurations",
]
check_cmd = "bird -p -c {{.src}}"
reload_cmd = "sv hup bird || true"
