# imagePullSecrets creates a secret
# containing the pull secret which is used to pull all images deployed by this helm chart.
# this field is a map where the key is the desired secret name and the value is the contents of the imagePullSecret.
#
# Example: --set-file imagePullSecrets.gcr=./pull-secret.json
imagePullSecrets: {}
# imagePullSecretReferences are configured on all images deployed by the chart.
# secrets specified here must already exist; they won't be created by the helm chart.
# imagePullSecretReferences are a slice of LocalObjectReferences, which is the same format they appear as on deployments.
#
# Example: --set imagePullSecretReferences[0].name=my-existing-secret
imagePullSecretReferences: []
installation:
  kubernetesProvider: ""
prometheusOperator:
  image: gcr.io/unique-caldron-775/cnx/tigera/prometheus-operator
  tag: master
prometheusConfigReloader:
  image: gcr.io/unique-caldron-775/cnx/tigera/prometheus-config-reloader
  tag: master
# Tolerations for the tigera/prometheus-operator pod to be scheduled on GKE Arm64 nodes.
# See: https://cloud.google.com/kubernetes-engine/docs/how-to/prepare-arm-workloads-for-deployment#multi-arch-schedule-any-arch
tolerations:
  - key: kubernetes.io/arch
    operator: Equal
    value: arm64
    effect: NoSchedule
