# imagePullSecrets creates a secret
# containing the pull secret which is used to pull all images deployed by this helm chart.
# this field is a map where the key is the desired secret name and the value is the contents of the imagePullSecret.
#
# Example: --set-file imagePullSecrets.gcr=./pull-secret.json
imagePullSecrets: {}
# imagePullSecretReferences are configured on all images deployed by the chart.
# secrets specified here must already exist; they won't be created by the helm chart.
# imagePullSecretReferences are a slice of LocalObjectReferences, which is the same format they appear as on deployments.
#
# Example: --set imagePullSecretReferences[0].name=my-existing-secret
imagePullSecretReferences: []
installation:
  kubernetesProvider: ""
prometheusOperator:
  image: quay.io/tigera/prometheus-operator
  tag: v3.20.0-1.0
prometheusConfigReloader:
  image: quay.io/tigera/prometheus-config-reloader
  tag: v3.20.0-1.0
