# This ConfigMap is used to configure a self-hosted {{include "variant_name" .}} installation.
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{include "variant_name" . | lower}}-config
  namespace: kube-system
data:
{{- if eq .Values.datastore "etcd" }}
  # Configure this with the location of your etcd cluster.
  etcd_endpoints: "{{ .Values.etcd.endpoints }}"

{{- if include "calico.etcd.tls" . }}

  etcd_ca: "/calico-secrets/etcd-ca"
  etcd_cert: "/calico-secrets/etcd-cert"
  etcd_key: "/calico-secrets/etcd-key"
{{- else }}
  # If you're using TLS enabled etcd uncomment the following.
  # You must also populate the Secret below with these files.
  etcd_ca: ""   # "/calico-secrets/etcd-ca"
  etcd_cert: "" # "/calico-secrets/etcd-cert"
  etcd_key: ""  # "/calico-secrets/etcd-key"
{{- end }}
{{- end }}
{{- if .Values.typha.enabled }}
  # You must set a non-zero value for Typha replicas below.
  typha_service_name: "{{ include "typha_service_name" . }}"
{{- else }}
  # Typha is disabled.
  typha_service_name: "none"

{{- end }}
{{- if eq .Values.network "calico" }}
  calico_backend: "bird"

  # Configure the MTU to use
  veth_mtu: "1440"
{{- end }}

  # The CNI network configuration to install on each node.  The special
  # values in this config will be automatically populated.
  cni_network_config: |-
    {
      "name": "k8s-pod-network",
      "cniVersion": "0.3.1",
      "plugins": [
        {
          "type": "calico",
          "log_level": "info",
  {{- if eq .Values.datastore "etcd" }}
          "etcd_endpoints": "__ETCD_ENDPOINTS__",
          "etcd_key_file": "__ETCD_KEY_FILE__",
          "etcd_cert_file": "__ETCD_CERT_FILE__",
          "etcd_ca_cert_file": "__ETCD_CA_CERT_FILE__",
  {{- else if eq .Values.datastore "kubernetes" }}
          "datastore_type": "kubernetes",
          "nodename": "__KUBERNETES_NODE_NAME__",
  {{- end }}
  {{- if eq .Values.network "calico" }}
          "mtu": __CNI_MTU__,
  {{- else if eq .Values.network "none" }}
          "mtu": 1500,
  {{- end }}
          "ipam": {
              "type": "{{ .Values.ipam }}"
              {{- if eq .Values.ipam "host-local" }},
              "subnet": "usePodCidr"
              {{- end }}
          },
          "policy": {
              "type": "k8s"
          },
          "kubernetes": {
              "kubeconfig": "__KUBECONFIG_FILEPATH__"
          }
        },
        {
          "type": "portmap",
          "snat": true,
          "capabilities": {"portMappings": true}
        }
      ]
    }
