apiVersion: v1
kind: Namespace
metadata:
  name: tigera-prometheus
  annotations:
{{- if eq .Values.installation.kubernetesProvider "openshift" }}
    openshift.io/node-selector: ""
{{- end }}
  labels:
    name: tigera-prometheus
{{- if eq .Values.installation.kubernetesProvider "openshift" }}
    openshift.io/run-level: "0"
{{- end }}
