elasticsearch:
  - ["POST", "_ml/datafeeds/$CLUSTER_NAME.datafeed-port_scan_pods/_stop", ""]
  - ["POST", "_ml/datafeeds/$CLUSTER_NAME.datafeed-ip_sweep_pods/_stop", ""]
  - ["POST", "_ml/datafeeds/$CLUSTER_NAME.datafeed-port_scan_external/_stop", ""]
  - ["POST", "_ml/datafeeds/$CLUSTER_NAME.datafeed-ip_sweep_external/_stop", ""]
  - ["POST", "_ml/datafeeds/$CLUSTER_NAME.datafeed-inbound_connection_spike/_stop", ""]
  - ["POST", "_ml/datafeeds/$CLUSTER_NAME.datafeed-service_bytes_anomaly/_stop", ""]
  - ["POST", "_ml/datafeeds/$CLUSTER_NAME.datafeed-pod_outlier_ip_activity/_stop", ""]

  - ["POST", "_ml/anomaly_detectors/$CLUSTER_NAME.port_scan_pods/_close", ""]
  - ["POST", "_ml/anomaly_detectors/$CLUSTER_NAME.ip_sweep_pods/_close", ""]
  - ["POST", "_ml/anomaly_detectors/$CLUSTER_NAME.port_scan_external/_close", ""]
  - ["POST", "_ml/anomaly_detectors/$CLUSTER_NAME.ip_sweep_external/_close", ""]
  - ["POST", "_ml/anomaly_detectors/$CLUSTER_NAME.inbound_connection_spike/_close", ""]
  - ["POST", "_ml/anomaly_detectors/$CLUSTER_NAME.service_bytes_anomaly/_close", ""]
  - ["POST", "_ml/anomaly_detectors/$CLUSTER_NAME.pod_outlier_ip_activity/_close", ""]

  - ["DELETE", "_ml/datafeeds/$CLUSTER_NAME.datafeed-port_scan_pods", ""]
  - ["DELETE", "_ml/datafeeds/$CLUSTER_NAME.datafeed-ip_sweep_pods", ""]
  - ["DELETE", "_ml/datafeeds/$CLUSTER_NAME.datafeed-port_scan_external", ""]
  - ["DELETE", "_ml/datafeeds/$CLUSTER_NAME.datafeed-ip_sweep_external", ""]
  - ["DELETE", "_ml/datafeeds/$CLUSTER_NAME.datafeed-inbound_connection_spike", ""]
  - ["DELETE", "_ml/datafeeds/$CLUSTER_NAME.datafeed-service_bytes_anomaly", ""]
  - ["DELETE", "_ml/datafeeds/$CLUSTER_NAME.datafeed-pod_outlier_ip_activity", ""]
  - ["DELETE", "_ml/anomaly_detectors/$CLUSTER_NAME.port_scan_pods", ""]
  - ["DELETE", "_ml/anomaly_detectors/$CLUSTER_NAME.ip_sweep_pods", ""]
  - ["DELETE", "_ml/anomaly_detectors/$CLUSTER_NAME.port_scan_external", ""]
  - ["DELETE", "_ml/anomaly_detectors/$CLUSTER_NAME.ip_sweep_external", ""]
  - ["DELETE", "_ml/anomaly_detectors/$CLUSTER_NAME.inbound_connection_spike", ""]
  - ["DELETE", "_ml/anomaly_detectors/$CLUSTER_NAME.service_bytes_anomaly", ""]
  - ["DELETE", "_ml/anomaly_detectors/$CLUSTER_NAME.pod_outlier_ip_activity", ""]

  - ["PUT", "_ml/anomaly_detectors/$CLUSTER_NAME.port_scan_pods", "./data/port-scan-pods-job.json"]
  - ["PUT", "_ml/datafeeds/$CLUSTER_NAME.datafeed-port_scan_pods", "./data/port-scan-pods-datafeed.json"]
  - ["PUT", "_ml/anomaly_detectors/$CLUSTER_NAME.ip_sweep_pods", "./data/ip-sweep-pods-job.json"]
  - ["PUT", "_ml/datafeeds/$CLUSTER_NAME.datafeed-ip_sweep_pods", "./data/ip-sweep-pods-datafeed.json"]
  - ["PUT", "_ml/anomaly_detectors/$CLUSTER_NAME.port_scan_external", "./data/port-scan-external-job.json"]
  - ["PUT", "_ml/datafeeds/$CLUSTER_NAME.datafeed-port_scan_external", "./data/port-scan-external-datafeed.json"]
  - ["PUT", "_ml/anomaly_detectors/$CLUSTER_NAME.ip_sweep_external", "./data/ip-sweep-external-job.json"]
  - ["PUT", "_ml/datafeeds/$CLUSTER_NAME.datafeed-ip_sweep_external", "./data/ip-sweep-external-datafeed.json"]
  - ["PUT", "_ml/anomaly_detectors/$CLUSTER_NAME.inbound_connection_spike", "./data/inbound-connection-spike-job.json"]
  - ["PUT", "_ml/datafeeds/$CLUSTER_NAME.datafeed-inbound_connection_spike", "./data/inbound-connection-spike-datafeed.json"]
  - ["PUT", "_ml/anomaly_detectors/$CLUSTER_NAME.service_bytes_anomaly", "./data/service-bytes-anomaly-job.json"]
  - ["PUT", "_ml/datafeeds/$CLUSTER_NAME.datafeed-service_bytes_anomaly", "./data/service-bytes-anomaly-datafeed.json"]
  - ["PUT", "_ml/anomaly_detectors/$CLUSTER_NAME.pod_outlier_ip_activity", "./data/pod-outlier-ip-activity-job.json"]
  - ["PUT", "_ml/datafeeds/$CLUSTER_NAME.datafeed-pod_outlier_ip_activity", "./data/pod-outlier-ip-activity-datafeed.json"]
kibana:
  - ["POST", "tigera-kibana/api/saved_objects/_bulk_create", "./data/api-kibana-dashboard.json"]
  - ["POST", "tigera-kibana/api/saved_objects/_bulk_create", "./data/tor-vpn-dashboard.json:"]
