- name: ingress-collector
  run:
    when: "${FORCE_RUN} or change_in(['/*', '/ingress-collector/', '/libcalico-go/lib/', '/felix/'], {exclude: ['/**/.gitignore', '/**/README.md', '/**/LICENSE'], branch_range: '${SEMAPHORE_GIT_COMMIT_RANGE}'})"
  dependencies:
    - Prerequisites
  task:
    prologue:
      commands:
        - cd ingress-collector
    jobs:
      - name: ingress-collector tests
        commands:
          - ../.semaphore/run-and-monitor ci.log make ci
      - name: Build binary
        matrix:
          - env_var: ARCH
            values:
              - arm64
        commands:
          - ../.semaphore/run-and-monitor build-$ARCH.log make build ARCH=$ARCH
