- name: prometheus-operator
  run:
    when: "${FORCE_RUN} or change_in(['/third_party/prometheus-operator/'], {exclude: ['/**/.gitignore', '/**/README.md', '/**/LICENSE']${DEFAULT_BRANCH}})"
  dependencies:
    - Prerequisites
  task:
    prologue:
      commands:
        - cd third_party/prometheus-operator
    jobs:
      - name: prometheus-operator tests
        commands:
          - ../../.semaphore/run-and-monitor ci.log make ci
      - name: Build image
        matrix:
          - env_var: ARCH
            values:
              - arm64
        commands:
          - ../../.semaphore/run-and-monitor build-$ARCH.log make image ARCH=$ARCH
