---
layout: null
---
{% helm calico-enterprise-ee --execute templates/manager.yaml --execute templates/compliance/compliance-server.yaml --execute templates/compliance/compliance-controller.yaml --execute templates/compliance/compliance-snapshotter.yaml --execute templates/compliance/compliance-reporter.yaml --execute templates/compliance/compliance-report-types.yaml %}
# TODO: fix bug where an empty helm includer doesn't render the manifest?
foo: bar
{% endhelm %}
