{{ if .Values.installation.enabled }}
{{ $installSpec := omit .Values.installation "enabled" }}
{{ $secrets := list }}
{{ range $name := keys .Values.imagePullSecrets -}}
{{ $item := dict "name" $name }}
{{ $secrets = append $secrets $item }}
{{ end }}
{{ $_ := set $installSpec "imagePullSecrets" $secrets }}

apiVersion: operator.tigera.io/v1
kind: Installation
metadata:
  name: default
{{ if .Values.techPreviewOptions.nodeApparmorPolicyName }}
  annotations:
    "tech-preview.operator.tigera.io/node-apparmor-profile": {{ .Values.techPreviewOptions.nodeApparmorPolicyName | quote}}
{{ end }}
spec:
{{ $installSpec | toYaml | indent 2 }}

{{ end }}
